# Generated by Django 5.0.8 on 2024-08-07 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='naturalidade',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
