# Generated by Django 5.0.8 on 2024-08-07 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrator', '0002_alter_pessoa_naturalidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='naturalidade_UF',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
